# Generated by Django 4.2.5 on 2023-10-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0003_alter_alumno_foto_alumno_alter_profesor_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anotacion', models.CharField(choices=[('bitacora', 'Bitácora'), ('anotacionNegativa', 'Anotación Negativa')], max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
                ('comentario', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.alumno')),
            ],
            options={
                'db_table': 'anotacion',
            },
        ),
    ]
