# Generated by Django 4.2.5 on 2023-10-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0004_anotacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='es_urgente',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='tipo_comunicado',
            field=models.CharField(choices=[('U', 'Urgente'), ('G', 'General')], default='G', max_length=1),
        ),
    ]
