# Generated by Django 4.2.5 on 2023-10-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0005_remove_comunicado_es_urgente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='tipo_anotacion',
            field=models.CharField(choices=[('bitacora', 'Bitácora'), ('anotacion negativa', 'Anotación Negativa')], max_length=20),
        ),
    ]
