# Generated by Django 4.2.5 on 2023-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0006_alter_anotacion_tipo_anotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='tipo_anotacion',
            field=models.CharField(choices=[('bitacora', 'Bitácora'), ('anotacionNegativa', 'Anotación Negativa')], max_length=20),
        ),
    ]
