# Generated by Django 4.2.5 on 2023-10-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0008_alter_anotacion_tipo_anotacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'periodo_semestral',
            },
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='clases_programadas',
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.curso')),
                ('periodo_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.periodosemestral')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
    ]
