# Generated by Django 4.2.5 on 2023-10-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0010_clase_materia_curso_asignaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='alumno',
            name='clase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.clase'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.materia'),
        ),
    ]
