# Generated by Django 4.2.5 on 2023-10-16 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RegistroAppDocente', '0011_remove_alumno_curso_remove_alumno_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellidoM',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellidoP',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='username',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellidoM',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellidoP',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='username',
        ),
        migrations.AddField(
            model_name='alumno',
            name='usera',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesor',
            name='userp',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
