# Generated by Django 4.2.5 on 2023-10-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0012_remove_alumno_apellidom_remove_alumno_apellidop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='clase',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.curso'),
        ),
    ]
