# Generated by Django 4.2.5 on 2023-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0013_remove_alumno_clase_alumno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='examen_final',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='parcial1',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='parcial2',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='parcial3',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='parcial4',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
