# Generated by Django 4.2.5 on 2023-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0014_alter_notas_examen_final_alter_notas_parcial1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='clase_iniciada',
            field=models.BooleanField(default=False),
        ),
    ]
