# Generated by Django 4.2.5 on 2023-10-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0015_clase_clase_iniciada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='periodo_semestral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistroAppDocente.periodosemestral'),
        ),
    ]
