# Generated by Django 4.2.2 on 2023-10-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0014_alter_alumno_id_alter_anotacion_id_alter_clase_id_and_more'),
        ('RegistroAppDocente', '0017_alter_clase_materia'),
    ]

    operations = [
    ]
