# Generated by Django 4.2.5 on 2023-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0018_merge_20231023_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto_alumno',
            field=models.ImageField(blank=True, default='media/foto/fotodefault.png', null=True, upload_to='foto'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='media/foto/fotodefault.png', null=True, upload_to='foto'),
        ),
    ]
