# Generated by Django 4.2.5 on 2023-10-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0019_clase_clase_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='clases_presente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='total_clases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
