# Generated by Django 4.2.5 on 2023-10-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAppDocente', '0020_alumno_clases_presente_alumno_total_clases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='clases_presente',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='total_clases',
        ),
    ]
